package internal

type ChatCompletionChunk struct {
	// List of completion choices (responses).
	Choices []ChatCompletionChunkChoice `json:"choices"`
	// Unix timestamp of when the completion was created in seconds
	Created int64 `json:"created"`
	// Unique identifier for the chat completion.
	ID string `json:"id"`
	// The model used to generate the completion.
	Model string `json:"model"`
	// Type of object returned, always "chat.completion".
	Object string `json:"object"`
	// Any of "auto", "default", "flex".
	ServiceTier string `json:"service_tier,omitempty"`
	// Internal system fingerprint identifying model and configuration.
	SystemFingerprint string `json:"system_fingerprint"`
	// Token usage statistics.
	Usage CompletionUsage `json:"usage"`
}

// ChatCompletionChunkChoice represents a single choice in a streaming response
type ChatCompletionChunkChoice struct {
	Index        int                 `json:"index"`
	Delta        ChatCompletionDelta `json:"delta"`
	FinishReason FinishReason        `json:"finish_reason"`
}

type ChatCompletionDelta struct {
	// The contents of the message.
	Content string `json:"content"`
	// The refusal message generated by the model.
	Refusal string `json:"refusal"`
	// The role of the author of this message.
	Role Role `json:"role"`
	// Deprecated
	FunctionCall ToolFunction `json:"function_call"`
	// The tool calls generated by the model, such as function calls.
	ToolCalls []ChatCompletionToolCall `json:"tool_calls"`
}
